// Copyright 2026 Kentrow
// SPDX-License-Identifier: Apache-2.0

// Command snapshotgen produces the route catalogue embedded in the binary.
//
// The catalogue is fetched from the API at startup; this snapshot is what the explorer
// falls back to when that fetch fails. It is regenerated by a
// maintainer rather than by CI, so that what ships is a reviewed file rather than
// whatever the API happened to answer during a build.
//
//	go run ./tools/snapshotgen
//
// The file it writes is committed, and the catalogue package embeds it, so the package
// does not compile without it. Restore it from git rather than deleting it before a
// regeneration.
package main

import (
	"compress/gzip"
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"time"

	sdk "github.com/ovh/go-ovh/ovh"

	"github.com/kentrow/keymaker/internal/catalog"
)

func main() {
	endpoint := flag.String("endpoint", "ovh-eu", "endpoint whose catalogue is captured")
	output := flag.String("output", "internal/catalog/snapshot.json.gz", "file to write")
	flag.Parse()

	base, ok := sdk.Endpoints[*endpoint]
	if !ok {
		log.Fatalf("unknown endpoint %q", *endpoint)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()

	snapshot, err := catalog.Fetch(ctx, &source{base: base})
	if err != nil {
		log.Fatalf("fetching the catalogue: %v", err)
	}

	// The captured file is a fallback, not a record of when a build ran; the day it was
	// taken is what the interface shows, and the time of day would only add noise to the
	// diff of a file that is otherwise stable.
	snapshot.Live = false
	snapshot.Taken = snapshot.Taken.Truncate(24 * time.Hour)

	if err := write(*output, snapshot); err != nil {
		log.Fatalf("writing %s: %v", *output, err)
	}
	log.Printf("wrote %s: %d routes across %d branches from %s",
		*output, len(snapshot.Routes), len(snapshot.Branches), *endpoint)
}

// source fetches the catalogue documents, which are unauthenticated. Signing is not
// reimplemented here: these two routes need none, which is why the generator runs
// without a credential at all.
type source struct {
	base string
}

func (s *source) Index(ctx context.Context) ([]byte, error) {
	return s.get(ctx, "/")
}

func (s *source) Schema(ctx context.Context, path string) ([]byte, error) {
	return s.get(ctx, path)
}

func (s *source) get(ctx context.Context, path string) ([]byte, error) {
	request, err := http.NewRequestWithContext(ctx, http.MethodGet, s.base+path, nil)
	if err != nil {
		return nil, err
	}
	response, err := http.DefaultClient.Do(request)
	if err != nil {
		return nil, err
	}
	defer func() { _ = response.Body.Close() }()

	if response.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("%s answered %s", path, response.Status)
	}
	return io.ReadAll(response.Body)
}

func write(path string, snapshot catalog.Snapshot) error {
	// #nosec G304 -- the destination is a flag because this tool is run by hand, by a
	// maintainer, to write a file inside the checkout. No untrusted input reaches it.
	file, err := os.Create(path)
	if err != nil {
		return err
	}
	defer func() { _ = file.Close() }()

	compressed, err := gzip.NewWriterLevel(file, gzip.BestCompression)
	if err != nil {
		return err
	}
	if err := json.NewEncoder(compressed).Encode(snapshot); err != nil {
		return err
	}
	if err := compressed.Close(); err != nil {
		return err
	}
	return file.Close()
}
